#%RAML 1.0 NamedExample


  -
    id: 1
    name: "sai"
    accountType: "business"
    address: "133,gran via, tX,USA"
    airMiles: 4
    created: 2023:09:22T12:00:00Z
  -
  
    id: 2
    name: "joy"
    accountType: "personal"
    address: "331 gran via"
    airMiles: 5
    created: 2023:09:22T12:00:00Z

